# Flower endpoints
###
GET http://localhost:8080/flowers


###
POST http://localhost:8080/flowers
Content-Type: application/json

{
  "id": 1,
  "sepalLength": 100,
  "color": "blue",
  "price": 100
}


# AppUser endpoints
###
GET http://localhost:8080/users

###
POST http://localhost:8080/users
Content-Type: application/json

{
  "id": 2,
  "email": "user2@email.com",
  "dob": "2001-09-11"
}
